(() => {
 'use strict';
 const canvas=document.getElementById('c'),ctx=canvas.getContext('2d');
 const buffer=document.createElement('canvas'),g=buffer.getContext('2d');
 const WORLD_W=2200,WORLD_H=620, palettes=[
  {sky:'#12123a',ground:'#0a0a26',body:'#ededed',roof:'#e8452f',door:'#1b1b1b',win:'#ffd93d',off:'#3a3a63',line:'#1b1b1b',building:'#2a2a55',dark:'#1a1a3a',light:'#4a4a88',cloud:'#fff',shadow:'#c8c8e0',road:'#222244',roadLine:'#ffd93d',tree:'#1a5a2a',treeDark:'#0d3d1a',car:'#e8452f',lamp:'#ffd93d'},
  {sky:'#f2a65a',ground:'#d97b3f',body:'#2b2b4a',roof:'#3d2b56',door:'#141428',win:'#ffe9a8',off:'#5a5a80',line:'#141428',building:'#3d2b56',dark:'#241a33',light:'#6b4a80',cloud:'#fff3e0',shadow:'#e0c8a0',road:'#4a2a1a',roadLine:'#ffe9a8',tree:'#2a5a2a',treeDark:'#1a3d1a',car:'#00d4ff',lamp:'#ffe9a8'},
  {sky:'#b8ecd8',ground:'#8fd9bd',body:'#1f6f5c',roof:'#ffd166',door:'#0d3b2f',win:'#fff',off:'#4d9c85',line:'#0d3b2f',building:'#2a6f5c',dark:'#1a4a3d',light:'#4a9c85',cloud:'#fff',shadow:'#b8e0d0',road:'#2a5a4a',roadLine:'#ffd166',tree:'#0d4a1a',treeDark:'#062a0d',car:'#ff4d94',lamp:'#ffd166'},
  {sky:'#ffd0e4',ground:'#f5a8c9',body:'#4a2c52',roof:'#ff4d94',door:'#2a142a',win:'#fff3a0',off:'#8a5a8a',line:'#2a142a',building:'#6b3a6b',dark:'#3d1a3d',light:'#9c5a9c',cloud:'#fff',shadow:'#e0b8d0',road:'#5a2a4a',roadLine:'#fff3a0',tree:'#3a5a2a',treeDark:'#1a3d0d',car:'#00d4ff',lamp:'#fff3a0'},
  {sky:'#0a3d91',ground:'#062a63',body:'#f5f5f5',roof:'#00d4ff',door:'#0a3d91',win:'#ffe066',off:'#8fb4e8',line:'#0a3d91',building:'#0a4a8a',dark:'#062a5a',light:'#2a6ab0',cloud:'#e0f0ff',shadow:'#a0c8e8',road:'#0a2a5a',roadLine:'#ffe066',tree:'#1a4a2a',treeDark:'#0a2a1a',car:'#ff4d94',lamp:'#ffe066'},
  {sky:'#f2f2f2',ground:'#d4d4d4',body:'#1a1a1a',roof:'#1a1a1a',door:'#f2f2f2',win:'#fff',off:'#4a4a4a',line:'#1a1a1a',building:'#2a2a2a',dark:'#0a0a0a',light:'#5a5a5a',cloud:'#fff',shadow:'#b0b0b0',road:'#3a3a3a',roadLine:'#fff',tree:'#2a4a2a',treeDark:'#1a2a1a',car:'#ff4d94',lamp:'#fff'}
 ];
 let W=0,H=0,COLS=300,ROWS=170,camX=WORLD_W/2-150,camY=WORLD_H*.55-85,palIndex=0,pal=palettes[0],drag=null,last=performance.now(),lastDream=last;
 const stars=Array.from({length:500},()=>({x:Math.random()*WORLD_W,y:Math.random()*WORLD_H*.55,a:.25+Math.random()*.75,s:1+Math.random()*3,p:.5+Math.random()*3,o:Math.random()*6.28,c:Math.random()<.2}));
 const glitter=Array.from({length:280},()=>({x:Math.random()*WORLD_W,y:WORLD_H*(.86+Math.random()*.14),p:Math.random()*6.28,s:Math.random()<.72?1:2,h:Math.random()*360}));
 const clouds=Array.from({length:20},(_,i)=>({x:35+i*112+(i%3)*19,y:25+(i%4)*18,w:30+(i%5)*5,h:7+(i%3),v:.7+(i%4)*.25}));
 const buildings=[];
 for(let i=0;i<54;i++){const x=18+i*41+(i%4)*7;if(Math.abs(x-WORLD_W/3)<80||Math.abs(x-WORLD_W*2/3)<80)continue;const h=30+(i*37)%78;buildings.push({x,y:WORLD_H*.8-h,w:16+(i*13)%23,h,cols:2+i%2,rows:3+i%4,far:i%3===0});}
 const trees=Array.from({length:58},(_,i)=>({x:24+i*38+(i%3)*5,y:WORLD_H*.8,h:9+i%9,pine:i%2===0})).filter(t=>Math.abs(t.x-WORLD_W/3)>70&&Math.abs(t.x-WORLD_W*2/3)>70);
 const cars=Array.from({length:14},(_,i)=>({x:Math.random()*WORLD_W,lane:i%2,dir:i%2?1:-1,v:.018+Math.random()*.025,color:i%3}));
 const windows=Array.from({length:5},(_,i)=>({on:Math.random()>.2,next:last+350+i*270}));
 function resize(){W=Math.max(1,innerWidth);H=Math.max(1,innerHeight);const dpr=Math.min(devicePixelRatio||1,2);COLS=Math.max(220,Math.min(360,Math.round(W/5)));ROWS=Math.max(140,Math.round(COLS*(H/W)));buffer.width=COLS;buffer.height=ROWS;canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.imageSmoothingEnabled=false;g.imageSmoothingEnabled=false;clamp();}
 function clamp(){camX=Math.max(0,Math.min(WORLD_W-COLS,camX));camY=Math.max(0,Math.min(WORLD_H-ROWS,camY));}
 function px(x,y,w,h,c,a=1){g.globalAlpha=a;g.fillStyle=c;g.fillRect(Math.round(x-camX),Math.round(y-camY),Math.round(w),Math.round(h));g.globalAlpha=1;}
 function diamond(x,y,size,color,a){const sx=Math.round(x-camX),sy=Math.round(y-camY),r=Math.max(1,Math.round(size));g.fillStyle=color;g.globalAlpha=a;for(let i=-r;i<=r;i++){const q=r-Math.abs(i);g.fillRect(sx-q,sy+i,q*2+1,1);}g.globalAlpha=1;}
 function drawSky(t){for(const s of stars){if(s.x<camX-5||s.x>camX+COLS+5||s.y<camY-5||s.y>camY+ROWS+5)continue;const wave=.5+.5*Math.sin(t*.001*s.p+s.o),color=s.c?`hsl(${(t*.04+s.o*40)%360} 90% 82%)`:'#fff';diamond(s.x,s.y,s.s*(.45+wave),color,s.a*(.3+.7*wave));}for(const c of clouds){px(c.x,c.y,c.w,c.h,pal.cloud);px(c.x,c.y+c.h-2,c.w,2,pal.shadow);px(c.x+c.w*.14,c.y-c.h*.45,c.w*.28,c.h*.65,pal.cloud);px(c.x+c.w*.52,c.y-c.h*.65,c.w*.3,c.h*.8,pal.cloud);}}
 function drawBuilding(b){const body=b.far?pal.dark:pal.building;px(b.x,b.y,b.w,b.h,body);px(b.x,b.y,b.w,2,pal.light);px(b.x+b.w-3,b.y,3,b.h,pal.dark);const ww=2,wh=3,gx=Math.max(2,Math.floor((b.w-b.cols*ww)/(b.cols+1))),gy=Math.max(2,Math.floor((b.h-b.rows*wh)/(b.rows+1)));for(let y=0;y<b.rows;y++)for(let x=0;x<b.cols;x++){const wx=b.x+gx+x*(ww+gx),wy=b.y+gy+y*(wh+gy);if(wy+wh<b.y+b.h-2)px(wx,wy,ww,wh,(x+y+Math.floor(b.x))%4?pal.win:pal.dark);}}
 function drawHouse(cx){const scale=.75,hw=Math.round(80*scale*.52),hh=Math.round(hw*.7),x=Math.round(cx-hw/2),y=WORLD_H*.8-4-hh,roofH=Math.round(hw*.38),eave=3;for(let row=0;row<roofH;row++){const f=row/(roofH-1),lx=x-eave+f*(hw/2+eave),rx=x+hw+eave-f*(hw/2+eave);px(lx,y-roofH+row+1,rx-lx,1,pal.roof);}px(x,y,hw,hh,pal.body);px(x,y,hw,1,pal.line);px(x,y+hh-1,hw,1,pal.line);const defs=[[.14,.16],[.42,.16],[.7,.16],[.14,.58],[.7,.58]];defs.forEach((d,i)=>{const wx=x+d[0]*hw,wy=y+d[1]*hh,ww=.16*hw,wh=.24*hh;px(wx,wy,ww,wh,windows[i].on?pal.win:pal.off);px(wx+ww/2,wy,1,wh,pal.line);px(wx,wy+wh/2,ww,1,pal.line);});px(x+.4*hw,y+.52*hh,.2*hw,.48*hh,pal.door);px(x+hw-10,y-roofH+4,4,9,pal.body);}
 function render(t){g.fillStyle=pal.sky;g.fillRect(0,0,COLS,ROWS);drawSky(t);px(0,WORLD_H*.86,WORLD_W,WORLD_H*.14,pal.ground);buildings.filter(b=>b.far).forEach(drawBuilding);buildings.filter(b=>!b.far).forEach(drawBuilding);for(const tr of trees){px(tr.x,tr.y-2,2,4,'#67431f');if(tr.pine){px(tr.x-3,tr.y-8,8,4,pal.tree);px(tr.x-2,tr.y-12,6,4,pal.treeDark);px(tr.x-1,tr.y-15,4,3,pal.tree);}else{px(tr.x-3,tr.y-9,7,7,pal.tree);px(tr.x-1,tr.y-12,5,5,pal.treeDark);}}const ry=WORLD_H*.8,rh=12;px(0,ry,WORLD_W,rh,pal.road);for(let x=0;x<WORLD_W;x+=14)px(x,ry+6,8,1,pal.roadLine);for(const c of cars){const y=ry+(c.lane?7:2);px(c.x,y,8,4,c.color===0?pal.car:c.color===1?'#4ecdc4':'#ffd166');px(c.x+2,y-1,4,1,'#eef');px(c.x+1,y+4,2,1,pal.dark);px(c.x+5,y+4,2,1,pal.dark);}for(const q of glitter){const a=.25+.75*Math.abs(Math.sin(t*.002+q.p));px(q.x,q.y,q.s,q.s,`hsl(${q.h} 90% 72%)`,a);}drawHouse(WORLD_W/3);drawHouse(WORLD_W*2/3);}
 function changeDream(){pal=palettes[++palIndex%palettes.length];lastDream=performance.now();windows.forEach((w,i)=>{w.on=false;w.next=lastDream+150+i*105;});}
 function update(t,dt){clouds.forEach(c=>{c.x+=c.v*dt*.02;if(c.x>WORLD_W+60)c.x=-60;});cars.forEach(c=>{c.x+=c.dir*c.v*dt;if(c.x>WORLD_W+20)c.x=-20;if(c.x<-20)c.x=WORLD_W+20;});windows.forEach(w=>{if(t>w.next){w.on=!w.on;w.next=t+350+Math.random()*1900;}});if(t-lastDream>12000)changeDream();}
 function frame(t){const dt=Math.min(50,t-last);last=t;update(t,dt);render(t);ctx.clearRect(0,0,W,H);ctx.drawImage(buffer,0,0,COLS,ROWS,0,0,W,H);requestAnimationFrame(frame);}
 addEventListener('resize',resize);addEventListener('message',e=>{if(e.origin===location.origin&&e.data==='quella:resize')resize();});addEventListener('wheel',e=>{e.preventDefault();let dx=e.deltaX,dy=e.deltaY;if(e.shiftKey)[dx,dy]=[dy,dx];camX+=dx*(COLS/W)*1.8;camY+=dy*(ROWS/H)*1.8;clamp();lastDream=performance.now();},{passive:false});
 addEventListener('keydown',e=>{const step=14;if(e.key==='ArrowLeft')camX-=step;else if(e.key==='ArrowRight')camX+=step;else if(e.key==='ArrowUp')camY-=step;else if(e.key==='ArrowDown')camY+=step;else if(e.code==='Space')changeDream();else return;e.preventDefault();clamp();});
 canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,cx:camX,cy:camY,moved:false,id:e.pointerId};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.moved ||= Math.abs(dx)+Math.abs(dy)>5;camX=drag.cx-dx*(COLS/W);camY=drag.cy-dy*(ROWS/H);clamp();});canvas.addEventListener('pointerup',e=>{if(drag&&!drag.moved)changeDream();drag=null;});canvas.addEventListener('pointercancel',()=>drag=null);
 resize();requestAnimationFrame(frame);
})();
